version: "3.8"

services:
  payment:
    build: payment_service
    volumes:
      - ./payment_service/data:/app/data
    environment:
      KINO_SERVICE_HOST: kino
    ports:
      - "8000:8000"
    depends_on:
      - kino
      - celery

  kino:
    build: kino_service
    environment:
      POSTGRES_HOST: kino_db
    env_file:
      - .env
    expose:
      - "50051"
    depends_on:
      - kino_db

  kino_db:
    image: postgres:13.3
    volumes:
      - kino_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:${POSTGRES_PORT}

  redis:
    image: redis:alpine
    expose:
      - "6379"

  celery:
    build: payment_service
    command: [ "celery", "-A", "payment_service", "worker", "--loglevel=info" ]
    volumes:
      - ./payment_service:/app
    environment:
      KINO_SERVICE_HOST: kino
    depends_on:
      - redis

  flower:
    build: payment_service
    command: [ "celery", "-A", "payment_service", "flower" ]
    volumes:
      - ./payment_service:/app
    depends_on:
      - redis
    ports:
      - "5555:5555"

volumes:
  kino_db_data:
