"""create tables

Revision ID: e635787b7783
Revises: 
Create Date: 2024-04-28 17:09:31.084551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e635787b7783'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    film_table = op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_film_id'), 'film', ['id'], unique=False)
    op.create_table('code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_id'), 'code', ['id'], unique=False)
    date_table = op.create_table('date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_date_id'), 'date', ['id'], unique=False)

    op.bulk_insert(film_table, [
        {'id': 1, 'name': 'Оппенгеймер', 'cost': 10.50},
        {'id': 2, 'name': 'Дюна: Часть вторая', 'cost': 15.75},
        {'id': 3, 'name': 'Интерстеллар', 'cost': 20.00}
    ])

    op.bulk_insert(date_table, [
        {'id': 1, 'film_id': 1, 'date': '2024-05-01 12:00:00'},
        {'id': 2, 'film_id': 1, 'date': '2024-05-05 15:30:00'},
        {'id': 3, 'film_id': 2, 'date': '2024-05-10 18:45:00'},
        {'id': 4, 'film_id': 2, 'date': '2024-05-15 20:00:00'},
        {'id': 5, 'film_id': 3, 'date': '2024-05-20 14:00:00'},
        {'id': 6, 'film_id': 3, 'date': '2024-05-25 16:30:00'}
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_date_id'), table_name='date')
    op.drop_table('date')
    op.drop_index(op.f('ix_code_id'), table_name='code')
    op.drop_table('code')
    op.drop_index(op.f('ix_film_id'), table_name='film')
    op.drop_table('film')
    # ### end Alembic commands ###
