# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iticket.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\riticket.proto\x1a\x1bgoogle/protobuf/empty.proto\".\n\x04\x46ilm\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x63ost\x18\x03 \x01(\x02\"-\n\x11PremieresResponse\x12\x18\n\tpremieres\x18\x01 \x03(\x0b\x32\x05.Film\"\x1c\n\x0c\x43odeResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\x1e\n\rDatesResponse\x12\r\n\x05\x64\x61tes\x18\x01 \x03(\t\"\x1e\n\x0bUserRequest\x12\x0f\n\x07\x66ilm_id\x18\x01 \x01(\x05\x32\x97\x01\n\x07ITicket\x12:\n\x0cgetPremieres\x12\x16.google.protobuf.Empty\x1a\x12.PremieresResponse\x12&\n\x07genCode\x12\x0c.UserRequest\x1a\r.CodeResponse\x12(\n\x08getDates\x12\x0c.UserRequest\x1a\x0e.DatesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iticket_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILM']._serialized_start=46
  _globals['_FILM']._serialized_end=92
  _globals['_PREMIERESRESPONSE']._serialized_start=94
  _globals['_PREMIERESRESPONSE']._serialized_end=139
  _globals['_CODERESPONSE']._serialized_start=141
  _globals['_CODERESPONSE']._serialized_end=169
  _globals['_DATESRESPONSE']._serialized_start=171
  _globals['_DATESRESPONSE']._serialized_end=201
  _globals['_USERREQUEST']._serialized_start=203
  _globals['_USERREQUEST']._serialized_end=233
  _globals['_ITICKET']._serialized_start=236
  _globals['_ITICKET']._serialized_end=387
# @@protoc_insertion_point(module_scope)
